apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-crud
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: student-crud
        image: student-crud:v1
        imagePullPolicy: IfNotPresent
        env:
        - name: DATABASE_URL
          value: "sqlite:////tmp/test.db"
